# Generated by Django 5.0.6 on 2024-09-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alumno_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.alumno'),
        ),
    ]
