# Generated by Django 5.0.6 on 2024-09-12 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_task_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.alumno'),
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.task'),
        ),
    ]
