# Generated by Django 5.0.6 on 2024-09-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_tutor_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.alumno'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.task'),
        ),
    ]
