# Generated by Django 5.0.6 on 2024-09-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_project_alumno_alter_project_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alumnos',
            field=models.ManyToManyField(blank=True, to='myapp.alumno'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='alumno',
            field=models.ManyToManyField(blank=True, to='myapp.alumno'),
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.ManyToManyField(blank=True, to='myapp.task'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='project',
            field=models.ManyToManyField(blank=True, to='myapp.project'),
        ),
    ]
