# Generated by Django 5.0.6 on 2024-09-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_task_alumnos_remove_project_alumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
    ]
