# Generated by Django 5.0.6 on 2024-10-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_criterios_niveldedesempeno_remove_alumno_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.grupo'),
        ),
    ]
