# Generated by Django 5.0.6 on 2024-10-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_project_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='project',
            field=models.ManyToManyField(blank=True, to='myapp.project'),
        ),
    ]
