# Generated by Django 5.0.6 on 2024-10-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_tutor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.tutor'),
            preserve_default=False,
        ),
    ]
