# Generated by Django 5.0.6 on 2024-10-09 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_project_grupo_remove_tutor_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.grupo'),
            preserve_default=False,
        ),
    ]
