# Generated by Django 5.0.6 on 2024-10-10 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_project_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='grupo',
        ),
        migrations.AddField(
            model_name='grupo',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.project'),
            preserve_default=False,
        ),
    ]
