# Generated by Django 5.0.6 on 2024-10-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alumno_apellido_alumno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptores',
            name='nivel_de_desempeno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.niveldedesempeno'),
            preserve_default=False,
        ),
    ]
