# Generated by Django 5.0.6 on 2024-11-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_descriptores_nivel_de_desempeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveldedesempeno',
            name='nivel',
            field=models.TextField(),
        ),
    ]
