# Generated by Django 5.0.6 on 2024-11-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_niveldedesempeno_descripcion_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveldedesempeno',
            name='descripcion_nivel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='niveldedesempeno',
            name='nivel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
