# Generated by Django 5.0.6 on 2024-11-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_niveldedesempeno_descripcion_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='calificacion_descriptivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
