# Generated by Django 5.0.6 on 2024-11-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_notas_calificacion_descriptivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='calificacion_descriptivo',
        ),
    ]
