# Generated by Django 5.0.6 on 2024-11-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_notas_calificacion_descriptivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
