# Generated by Django 5.0.6 on 2024-11-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_notas_pareja_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='pareja_id',
        ),
    ]
