# Generated by Django 5.0.6 on 2024-11-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_notas_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
