# Generated by Django 5.0.6 on 2025-01-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_rubrica_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackHistory',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.grupo')),
            ],
        ),
    ]
