# Generated by Django 5.0.6 on 2025-01-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_feedbackhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='explicacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
