# Generated by Django 5.0.6 on 2025-01-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_calificacion_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='corregida',
            field=models.BooleanField(default=False),
        ),
    ]
