# Generated by Django 5.0.6 on 2025-01-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_notas_corregida'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackhistory',
            name='criterio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.criterios'),
            preserve_default=False,
        ),
    ]
