# Generated by Django 5.0.6 on 2025-01-05 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_feedbackhistory_criterio'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='criterio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.criterios'),
            preserve_default=False,
        ),
    ]
