# Generated by Django 5.0.6 on 2025-01-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_notas_criterio'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackhistory',
            name='nivel_de_desempeno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.niveldedesempeno'),
            preserve_default=False,
        ),
    ]
