# Generated by Django 5.0.6 on 2025-01-14 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_feedbackhistory_nivel_de_desempeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackhistory',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.alumno'),
            preserve_default=False,
        ),
    ]
